apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-live2d
  labels:
    halo.run/role-template: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
  annotations:
    rbac.authorization.halo.run/module: "Live2d"
    rbac.authorization.halo.run/display-name: "Live2d"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:PluginLive2d:live2d"]
rules:
  - apiGroups: [ "api.live2d.halo.run" ]
    resources: [ "live2d/chat-process" ]
    resourceNames: [ "ai" ]
    verbs: [ "create" ]
