apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginLive2d
spec:
  enabled: true
  version: 1.1.0
  requires: ">=2.4.0"
  author:
    name: LIlGG
    website: https://lixingyong.com
  logo: logo.gif
  settingName: plugin-live2d-settings
  configMapName: plugin-live2d-configs
  homepage: https://github.com/LIlGG/plugin-live2d
  displayName: "live2d 看板娘"
  description: "为主题增加一个萌萌哒的看板娘吧！ʕ̯•͡ˑ͓•̯᷅ʔ"
  license:
    - name: "MIT"
