import type { Live2dConfig } from "@/live2d/context/config-context";

export const DEFAULT_TOOL_NAMES = [
  "hitokoto",
  "asteroids",
  "switch-model",
  "switch-texture",
  "photo",
  "info",
  "quit",
] as const;

export const createDefaultLive2dConfig = (): Live2dConfig => ({
  apiPath: "https://live2d.fghrsh.net/api/",
  live2dLocation: "left",
  consoleShowStatus: import.meta.env.DEV ?? false,
  isForceUseDefaultConfig: false,
  modelId: 1,
  modelTexturesId: 53,
  tipsPath: "",
  selectorTips: [],
  backSite: true,
  backSiteTip: "",
  copyContent: true,
  copyContentTip: "",
  openConsole: true,
  openConsoleTip: "",
  firstOpenSite: true,
  isTools: true,
  tools: [...DEFAULT_TOOL_NAMES],
  isAiChat: true,
  accessMode: "anonymous_chat",
  agent: {
    builtIn: {
      pageContext: true,
      haloNavigation: true,
      haloContentSearch: true,
      networkAccess: false,
      commentCapability: "assist",
    },
    aiTools: [],
    toolSecurity: {
      allowedExternalOrigins: [],
      allowNewTab: false,
    },
    haloSearch: {
      allowedTypes: ["post.content.halo.run", "singlepage.content.halo.run"],
      defaultLimit: 5,
    },
    haloResourceDetail: {
      maxContentChars: 3000,
    },
  },
  chunkTimeout: 10,
  showChatMessageTimeout: 10,
  autoContinuationMessageMinVisibleMs: 1500,
  requestAcceptedMessage: "收到啦，马上就来陪你啦～",
  reasoningMessages: [
    "我正在认真想一想～",
    "让我整理一下思路，很快就好～",
    "稍等一下，我正在组织语言呢～",
  ],
  reasoningMessageInterval: 5,
  chatContextRounds: 20,
  screenshotName: "live2d",
  filterQuality: "high",
  proceduralAnimation: {
    enabled: true,
    breathing: {
      enabled: true,
      period: 3000,
      amplitude: 0.15,
    },
    blink: {
      enabled: false,
      minInterval: 2000,
      maxInterval: 6000,
      duration: 150,
    },
    eyeTracking: {
      enabled: true,
      maxAngleX: 15,
      maxAngleY: 10,
      maxEyeBallX: 1.5,
      maxEyeBallY: 1.5,
      smoothing: 0.15,
    },
  },
  motionLayers: {
    enabled: true,
    layers: {
      idle: { priority: 1 },
      expression: { priority: 2 },
      talk: { priority: 3 },
      gesture: { priority: 4 },
      physics: { priority: 5 },
    },
    defaultCrossfadeDuration: 300,
  },
  behaviorFSM: {
    enabled: true,
    initialState: "idle",
    defaultDebounceMs: 300,
  },
  emotionTimeline: {
    enabled: true,
    defaultDuration: 800,
    minDuration: 200,
    defaultEasing: "easeOut",
    idleReturnDelay: 3000,
  },
  devTools: {
    enabled: false,
  },
});
