// This file is auto-generated by scripts/generate-custom-tool-actions.mjs.
// Do not edit it manually.

import actionDefinition0 from "./actions/emit-event";
import actionDefinition1 from "./actions/load-model";
import actionDefinition2 from "./actions/open-url";
import actionDefinition3 from "./actions/screenshot";
import actionDefinition4 from "./actions/send-message";
import actionDefinition5 from "./actions/switch-model";
import actionDefinition6 from "./actions/switch-texture";
import actionDefinition7 from "./actions/toggle-chat";
import actionDefinition8 from "./actions/widget-visibility";

export const customToolActionDefinitions = [
  actionDefinition0,
  actionDefinition1,
  actionDefinition2,
  actionDefinition3,
  actionDefinition4,
  actionDefinition5,
  actionDefinition6,
  actionDefinition7,
  actionDefinition8,
] as const;

export type CustomToolAction = Exclude<
  ReturnType<(typeof customToolActionDefinitions)[number]["normalize"]>,
  undefined
>;

export type CustomToolActionType = CustomToolAction["type"];

export const CUSTOM_TOOL_ACTION_TYPES = customToolActionDefinitions.map(
  (definition) => definition.type,
) as CustomToolActionType[];
