name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-ci.yaml@v4
    with:
      ui-path: "."
      pnpm-version: "10.33.4"
      node-version: "24"
      java-version: "21"
